---
apiVersion: v1
kind: Pod
metadata:
  name: database_pod
  labels:
    project: novinano_ts
spec:
  containers:
    - name: database
      image: mysql:5.6
      env:
        - name: MYSQL_DATABASE
          value: novinano_project
        - name: MYSQL_USER
          value: test
        - name: MYSQL_PASSWORD
          value: test123
        - name: MYSQL_ROOT_PASSWORD
          value: root
      ports:
        - containerPort: 3306   
---