---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novinano-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: novinano-project
  template:
    metadata:
      labels:
        project: novinano-project
    spec:
      containers:
        - name: database
          image: mysql:5.6
          env:
            - name: MYSQL_DATABASE
              value: novinano_project
            - name: MYSQL_USER
              value: test
            - name: MYSQL_PASSWORD
              value: test123
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306   
---