---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: database-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      database_mysql: db-mysql
  template:
    metadata:
      labels:
        database_mysql: db-mysql
    spec:
      containers:
        - name: database
          image: mysql:5.6
          env:
            - name: MYSQL_DATABASE
              value: project
            - name: MYSQL_USER
              value: test
            - name: MYSQL_PASSWORD
              value: test123
            - name: MYSQL_ROOT_PASSWORD
              value: root
          ports:
            - containerPort: 3306   
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: novinano-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      project: novinano-project
  template:
    metadata:
      labels:
        project: novinano-project
    spec:
      containers:
        - name: novinano
          image: cimbel/novinanots:v1
          ports:
            - containerPort: 80
            - containerPort: 443   
---